version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/foodgram/.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
      - backend
      - nginx

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:18000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "18000:18000"
    depends_on:
      - db
    env_file:
      - ../backend/foodgram/.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend