# Generated by Django 2.2.6 on 2022-01-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriterecipe',
            old_name='is_favourite',
            new_name='is_favorited',
        ),
    ]
