# Generated by Django 2.2.6 on 2021-12-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211221_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиенты', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'ordering': ('recipe',), 'verbose_name': 'Рецепт -> Ингредиент', 'verbose_name_plural': 'Рецепт -> Ингредиент'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'ordering': ('recipe',), 'verbose_name': 'Рецепт -> Тег', 'verbose_name_plural': 'Рецепт -> Тег'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
