# Generated by Django 2.2.6 on 2022-01-04 18:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20220104_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Subscription',
        ),
    ]
