# Generated by Django 2.2.6 on 2022-01-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220104_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
